name: test all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@b00551441a6fa3d528f3443dbff264a934b6e316
        with:
          bundler-cache: true

      - name: Run tests
        run: |
          rake test
